name: vips
description: Dart API for the VIPS image processing library.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.3.0-0

dependencies:
  logging: ^1.2.0
  native_assets_cli: ^0.3.0
  native_toolchain_c:
    path: ../dart/native/pkgs/native_toolchain_c
  ffi: ^2.1.0
  meta: ^1.10.0

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^2.0.0
  test: ^1.21.0

ffigen:
  output: lib/src/bindings.dart
  preamble: |
    // ignore_for_file: unused_element, unused_field
  compiler-opts:
    - -Ivendor/libvips/build/install/include
    - -Ivendor/libvips/build/install/include/glib-2.0
    - -Ivendor/libvips/build/install/lib/glib-2.0/include
  exclude-all-by-default: true
  headers:
    entry-points:
      - vendor/libvips/build/install/include/glib-2.0/glib.h
      - vendor/libvips/build/install/include/vips/vips.h
  functions:
    include:
      - g_object_get_property
      - g_object_ref
      - g_object_set_property
      - g_object_unref
      - g_strfreev
      - g_value_get_boolean
      - g_value_get_boxed
      - g_value_get_double
      - g_value_get_enum
      - g_value_get_int
      - g_value_get_object
      - g_value_get_string
      - g_value_get_uint64
      - g_value_init
      - g_value_set_boolean
      - g_value_set_boxed
      - g_value_set_double
      - g_value_set_enum
      - g_value_set_int
      - g_value_set_object
      - g_value_set_string
      - g_value_set_uint64
      - g_value_unset
      - vips_.*_get_type
      - vips_area_copy
      - vips_area_unref
      - vips_blob_new
      - vips_cache_operation_build
      - vips_colourspace_issupported
      - vips_error_buffer_copy
      - vips_image_get_fields
      - vips_image_guess_interpretation
      - vips_image_new
      - vips_image_new_from_file
      - vips_init
      - vips_object_unref_outputs
      - vips_operation_new
  typedefs:
    include:
      - GValue
      - VipsArea
      - VipsBlob
      - VipsImage
      - VipsOperation
  enums:
    include:
      - VipsDirection
  macros:
    include:
      - G_TYPE_.*
      - G_CONNECT_.*
  ffi-native:
